GLOBAL_INCLUDES		+= ./autotiler/include/
GLOBAL_INCLUDES		+= ./autotiler/generators/CNN/
GLOBAL_INCLUDES		+= ./autotiler/generators/FFT2D/
GLOBAL_INCLUDES		+= ./autotiler/generators/IntegralImg/
GLOBAL_INCLUDES		+= ./autotiler/generators/MatAdd/
#GLOBAL_INCLUDES		+= ./autotiler/generators/Resize

#$(NAME)_SOURCES     +=./autotiler/generators/MatAdd/MatAddGenerator.c
#$(NAME)_SOURCES     +=./autotiler/generators/MatAdd/MatAddBasicKernels.c
$(NAME)_SOURCES     +=./autotiler/generators/CNN/CNN_Conv_DP_BasicKernels.c
$(NAME)_SOURCES     +=./autotiler/generators/CNN/CNN_Pooling_BasicKernels.c
$(NAME)_SOURCES     +=./autotiler/generators/CNN/CNN_Generators.c
$(NAME)_SOURCES     +=./autotiler/generators/CNN/CNN_SoftMax.c
$(NAME)_SOURCES     +=./autotiler/generators/CNN/CNN_Conv_BasicKernels.c
$(NAME)_SOURCES     +=./autotiler/generators/CNN/CNN_BiasReLULinear_BasicKernels.c
$(NAME)_SOURCES     +=./autotiler/generators/CNN/CNN_MatAlgebra.c
#$(NAME)_SOURCES     +=./autotiler/generators/FFT2D/FFT2DGenerator.c
#$(NAME)_SOURCES     +=./autotiler/generators/FFT2D/FFTBasicKernels.c
#$(NAME)_SOURCES     +=./autotiler/generators/FFT2D/FFTScalarBasicKernels.c
#$(NAME)_SOURCES     +=./autotiler/generators/FFT2D/twiddles_gen/GenTwid_Swap.c
$(NAME)_SOURCES     +=./autotiler/generators/Resize/ResizeBasicKernels.c
$(NAME)_SOURCES     +=./autotiler/generators/Resize/ResizeGenerator.c
$(NAME)_SOURCES     +=./autotiler/generators/IntegralImg/IntegralImgBasicKernels.c
$(NAME)_SOURCES     +=./autotiler/generators/IntegralImg/IntegralImgGenerator.c
