NAME := spim_full_duplex

$(NAME)_MBINS_TYPE := app
$(NAME)_VERSION := 1.0.0
$(NAME)_SUMMARY := spim_full_duplex
$(NAME)_SOURCES := test.c

$(NAME)_COMPONENTS += osal_aos

GLOBAL_CFLAGS += -DSPIM_ITF=0 -DSPIM_CS=1 -DPRINTF_GVSOC -DSYNC_CS_AUTO=0 #-DSYNC_CS_KEEP #-DASYNC_CS_AUTO

GLOBAL_DEFINES += AOS_NO_WIFI

GLOBAL_INCLUDES += ./
